[package]
name = "racp-core"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
racp-contract = { path = "../racp-contract" }
serde.workspace = true
serde_json.workspace = true
url.workspace = true
chrono.workspace = true
fs2.workspace = true
whoami = "1"
rustls.workspace = true
rustls-pemfile.workspace = true

[target.'cfg(unix)'.dependencies]
libc = "0.2"
[target.'cfg(windows)'.dependencies]
windows-sys = { version = "0.61", features = ["Win32_Security_Cryptography", "Win32_Foundation", "Win32_Storage_FileSystem"] }
[dev-dependencies]
tempfile.workspace = true
