/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/v1/management/status": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Management Status */
    get: operations["management_status_api_v1_management_status_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/management/settings": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Management Settings */
    get: operations["management_settings_api_v1_management_settings_get"];
    /** Management Settings Apply */
    put: operations["management_settings_apply_api_v1_management_settings_put"];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/management/settings/stage": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Management Settings Stage */
    post: operations["management_settings_stage_api_v1_management_settings_stage_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/management/devices": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Management Devices */
    get: operations["management_devices_api_v1_management_devices_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/management/users": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Management Users */
    get: operations["management_users_api_v1_management_users_get"];
    put?: never;
    /** Management User Create */
    post: operations["management_user_create_api_v1_management_users_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/management/users/{user_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** Management User Patch */
    patch: operations["management_user_patch_api_v1_management_users__user_id__patch"];
    trace?: never;
  };
  "/api/v1/management/groups": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Management Groups */
    get: operations["management_groups_api_v1_management_groups_get"];
    put?: never;
    /** Management Group Create */
    post: operations["management_group_create_api_v1_management_groups_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/management/groups/{group_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** Management Group Patch */
    patch: operations["management_group_patch_api_v1_management_groups__group_id__patch"];
    trace?: never;
  };
  "/api/v1/management/devices/{device_id}/groups": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** Management Device Groups */
    patch: operations["management_device_groups_api_v1_management_devices__device_id__groups_patch"];
    trace?: never;
  };
  "/api/v1/management/logs": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Management Logs */
    get: operations["management_logs_api_v1_management_logs_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/management/log-exports": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Management Log Export Create */
    post: operations["management_log_export_create_api_v1_management_log_exports_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/management/log-exports/{export_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Management Log Export Status */
    get: operations["management_log_export_status_api_v1_management_log_exports__export_id__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/management/log-exports/{export_id}/download": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Management Log Export Download */
    get: operations["management_log_export_download_api_v1_management_log_exports__export_id__download_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/management/backups": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Management Backups */
    get: operations["management_backups_api_v1_management_backups_get"];
    put?: never;
    /** Management Backup Create */
    post: operations["management_backup_create_api_v1_management_backups_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/management/backups/{backup_id}/restore-preview": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Management Restore Preview */
    get: operations["management_restore_preview_api_v1_management_backups__backup_id__restore_preview_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/management/restores": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Management Restore Create */
    post: operations["management_restore_create_api_v1_management_restores_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/management/maintenance-jobs/{job_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Management Maintenance Job */
    get: operations["management_maintenance_job_api_v1_management_maintenance_jobs__job_id__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/management/updates/status": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Management Update Status */
    get: operations["management_update_status_api_v1_management_updates_status_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/management/updates/check": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Management Update Check */
    post: operations["management_update_check_api_v1_management_updates_check_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/management/updates/apply": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Management Update Apply */
    post: operations["management_update_apply_api_v1_management_updates_apply_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/management/support-bundles": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Management Support Bundle Create */
    post: operations["management_support_bundle_create_api_v1_management_support_bundles_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/management/support-bundles/{bundle_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Management Support Bundle Download */
    get: operations["management_support_bundle_download_api_v1_management_support_bundles__bundle_id__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/console/setup-token": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Console Setup */
    post: operations["console_setup_api_v1_console_setup_token_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/console/session": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Console Session */
    get: operations["console_session_api_v1_console_session_get"];
    put?: never;
    /** Console Login */
    post: operations["console_login_api_v1_console_session_post"];
    /** Console Logout */
    delete: operations["console_logout_api_v1_console_session_delete"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/console/session/activity": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Console Activity */
    post: operations["console_activity_api_v1_console_session_activity_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/events": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Console Events */
    get: operations["console_events_api_v1_events_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/events": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Console Events */
    get: operations["console_events_events_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/doctor": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Doctor */
    get: operations["doctor_api_v1_doctor_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/healthz": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Health */
    get: operations["health_healthz_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/readyz": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Ready */
    get: operations["ready_readyz_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/enrollment-tokens": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Enrollment */
    post: operations["enrollment_api_v1_enrollment_tokens_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/agent/v1/enroll": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Enroll */
    post: operations["enroll_agent_v1_enroll_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/devices": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Devices */
    get: operations["devices_api_v1_devices_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/devices/{device_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Device */
    get: operations["device_api_v1_devices__device_id__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/devices/{device_id}/revoke": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Revoke */
    post: operations["revoke_api_v1_devices__device_id__revoke_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/devices/{device_id}/handles": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Device Handles */
    get: operations["device_handles_api_v1_devices__device_id__handles_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/handles/{handle_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Resource Handle */
    get: operations["resource_handle_api_v1_handles__handle_id__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/devices/{device_id}/credentials/rotate": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Rotate */
    post: operations["rotate_api_v1_devices__device_id__credentials_rotate_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/operations": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Execute */
    post: operations["execute_api_v1_operations_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/operations/{operation_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Operation */
    get: operations["operation_api_v1_operations__operation_id__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/operations/{operation_id}/cancel": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Cancel */
    post: operations["cancel_api_v1_operations__operation_id__cancel_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/operations/{operation_id}/resolutions": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Resolutions */
    get: operations["resolutions_api_v1_operations__operation_id__resolutions_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/operations/{operation_id}/outputs": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Operation Outputs */
    get: operations["operation_outputs_api_v1_operations__operation_id__outputs_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/jobs/{job_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Job */
    get: operations["job_api_v1_jobs__job_id__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/jobs/{job_id}/cancel": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Cancel Job */
    post: operations["cancel_job_api_v1_jobs__job_id__cancel_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/jobs": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Jobs */
    get: operations["jobs_api_v1_jobs_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/approvals": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Approvals */
    get: operations["approvals_api_v1_approvals_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/approvals/{approval_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Approval */
    get: operations["approval_api_v1_approvals__approval_id__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/approvals/{approval_id}/approve": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Approve */
    post: operations["approve_api_v1_approvals__approval_id__approve_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/approvals/{approval_id}/deny": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Deny */
    post: operations["deny_api_v1_approvals__approval_id__deny_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/approvals/{approval_id}/execute": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Execute Approved */
    post: operations["execute_approved_api_v1_approvals__approval_id__execute_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/audit": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Audit */
    get: operations["audit_api_v1_audit_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/agent/v1/operations/{operation_id}/output": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Upload Output */
    post: operations["upload_output_agent_v1_operations__operation_id__output_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/artifacts/{artifact_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Artifact */
    get: operations["artifact_api_v1_artifacts__artifact_id__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/artifacts/{artifact_id}/content": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Content */
    get: operations["content_api_v1_artifacts__artifact_id__content_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/artifacts": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Artifact List */
    get: operations["artifact_list_api_v1_artifacts_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/artifact-transfers": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Transfer Create */
    post: operations["transfer_create_api_v1_artifact_transfers_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/artifact-transfers/{transfer_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Transfer Get */
    get: operations["transfer_get_api_v1_artifact_transfers__transfer_id__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/artifact-transfers/{transfer_id}/authorize": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Transfer Authorize */
    post: operations["transfer_authorize_api_v1_artifact_transfers__transfer_id__authorize_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/artifact-transfers/{transfer_id}/content": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Transfer Download */
    get: operations["transfer_download_api_v1_artifact_transfers__transfer_id__content_get"];
    /** Transfer Put */
    put: operations["transfer_put_api_v1_artifact_transfers__transfer_id__content_put"];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/artifact-transfers/{transfer_id}/complete": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Transfer Complete */
    post: operations["transfer_complete_api_v1_artifact_transfers__transfer_id__complete_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/artifacts/gc": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Artifact Gc */
    post: operations["artifact_gc_api_v1_artifacts_gc_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** ApprovalView */
    ApprovalView: {
      /** Id */
      id: string;
      /** Operation Id */
      operation_id: string;
      /** Digest */
      digest: string;
      /** Expires */
      expires: number;
      /** State */
      state: string;
      /** Device Id */
      device_id: string;
      /** Device Name */
      device_name: string;
      /** Execution Identity */
      execution_identity: string | null;
      /** Agent Boot Id */
      agent_boot_id: string | null;
      /** Operation */
      operation: string;
      /** Profile */
      profile: string;
      /** Target */
      target: {
        [key: string]: unknown;
      };
    };
    /** ArtifactView */
    ArtifactView: {
      /** Id */
      id: string;
      /** Operation Id */
      operation_id: string;
      /** Device Id */
      device_id: string;
      /** Owner Id */
      owner_id: string;
      /** Sha256 */
      sha256: string;
      /** Size Bytes */
      size_bytes: number;
      /** Created At */
      created_at: string;
      /** Media Type */
      media_type: string;
      /** State */
      state: string;
      /** Expires At */
      expires_at: string;
    };
    /** AuditView */
    AuditView: {
      /** Id */
      id: string;
      /** Timestamp */
      timestamp: string;
      /** Event */
      event: string;
      /** Device Id */
      device_id: string;
      /** Operation Id */
      operation_id: string;
      /** Operation */
      operation: string;
      /** Trace Id */
      trace_id: string;
      /** Request Id */
      request_id: string;
      /** Owner Id */
      owner_id: string;
      /** Summary */
      summary: {
        [key: string]: unknown;
      };
    };
    /** BackupCreateRequest */
    BackupCreateRequest: {
      /** Idempotency Key */
      idempotency_key: string;
    };
    /** BackupSetView */
    BackupSetView: {
      /** Id */
      id: string;
      /**
       * State
       * @enum {string}
       */
      state: "COMPLETE" | "INCOMPLETE" | "CORRUPT";
      /** Manifest Path */
      manifest_path: string;
      /** Sha256 */
      sha256: string;
      /** Schema Version */
      schema_version: number;
      /** Instance Id */
      instance_id: string;
      /** Created At */
      created_at: string;
    };
    /** ConfigCheck */
    ConfigCheck: {
      /** Valid */
      valid: boolean;
      /** Errors */
      errors?: string[];
      /** Warnings */
      warnings?: string[];
      /**
       * Restart Required
       * @default false
       */
      restart_required: boolean;
    };
    /** ConsoleLogin */
    ConsoleLogin: {
      /** Setup Secret */
      setup_secret: string;
    };
    /** ConsoleSession */
    ConsoleSession: {
      /** Owner Id */
      owner_id: string;
      /** Csrf Token */
      csrf_token: string;
      /**
       * Idle Seconds
       * @default 1800
       */
      idle_seconds: number;
      /**
       * Absolute Seconds
       * @default 43200
       */
      absolute_seconds: number;
      /** Expires At */
      expires_at: string;
    };
    /** DeviceGroupCreateRequest */
    DeviceGroupCreateRequest: {
      /** Name */
      name: string;
      /** Tags */
      tags?: string[];
    };
    /** DeviceGroupPatchRequest */
    DeviceGroupPatchRequest: {
      /** Expected Revision */
      expected_revision: number;
      /** Name */
      name?: string | null;
      /** Tags */
      tags?: string[] | null;
      /** Device Ids */
      device_ids?: string[] | null;
    };
    /** DeviceGroupView */
    DeviceGroupView: {
      /** Id */
      id: string;
      /** Name */
      name: string;
      /** Tags */
      tags?: string[];
      /** Device Ids */
      device_ids?: string[];
      /** Revision */
      revision: number;
    };
    /** DeviceGroupsPatch */
    DeviceGroupsPatch: {
      /** Group Ids */
      group_ids?: string[];
      /** Expected Revision */
      expected_revision: number;
    };
    /** DeviceMetadataView */
    DeviceMetadataView: {
      /** Device Id */
      device_id: string;
      /** Group Ids */
      group_ids?: string[];
      /** Tags */
      tags?: string[];
      /** Revision */
      revision: number;
    };
    /** DevicePage */
    DevicePage: {
      /** Items */
      items: components["schemas"]["ManagedDeviceView"][];
      /** Next Cursor */
      next_cursor?: string | null;
    };
    /** DeviceView */
    DeviceView: {
      /** Id */
      id: string;
      /** Name */
      name: string;
      /** Owner Id */
      owner_id: string;
      /** Revoked */
      revoked: number;
      /** Epoch */
      epoch: number;
      /** Info */
      info: {
        [key: string]: unknown;
      };
    };
    /** DoctorView */
    DoctorView: {
      /**
       * Status
       * @enum {string}
       */
      status: "healthy" | "degraded";
      /**
       * Protocol
       * @default 1
       */
      protocol: number;
      /** Owner Id */
      owner_id: string;
      /** Gateway */
      gateway: {
        [key: string]: unknown;
      };
      /** Devices */
      devices: {
        [key: string]: unknown;
      }[];
      /** Limitations */
      limitations: string[];
    };
    /** EnrollInput */
    EnrollInput: {
      /** Token */
      token: string;
    };
    /** EnrollmentInput */
    EnrollmentInput: {
      /** Name */
      name: string;
      /**
       * Include Connection File
       * @default false
       */
      include_connection_file: boolean;
    };
    /** GatewayStatusView */
    GatewayStatusView: {
      /**
       * Lifecycle
       * @enum {string}
       */
      lifecycle:
        | "STARTING"
        | "READY"
        | "DRAINING"
        | "STOPPING"
        | "STOPPED"
        | "DEGRADED"
        | "FAILED";
      /** Ready */
      ready: boolean;
      /** Version */
      version: string;
      /** Instance Id */
      instance_id?: string | null;
      /**
       * Mode
       * @enum {string}
       */
      mode: "service" | "portable" | "legacy";
      /**
       * Setup Mode
       * @enum {string}
       */
      setup_mode: "local_owner" | "oidc";
      /**
       * Database
       * @enum {string}
       */
      database: "ready" | "busy" | "failed";
      /**
       * Mcp
       * @enum {string}
       */
      mcp: "owner_bearer" | "oauth" | "not_configured";
      /** Settings Revision */
      settings_revision: number;
      /** Connected Devices */
      connected_devices: number;
      /** Total Devices */
      total_devices: number;
      /** Event Streams */
      event_streams: number;
      /**
       * Tls Configured
       * @default false
       */
      tls_configured: boolean;
      /** Tls Expires At */
      tls_expires_at?: string | null;
      /** Disk Free Bytes */
      disk_free_bytes?: number | null;
      /** Warnings */
      warnings?: string[];
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][];
    };
    /**
     * JobState
     * @enum {string}
     */
    JobState:
      | "QUEUED"
      | "RUNNING"
      | "WAITING"
      | "CANCEL_REQUESTED"
      | "RECONCILING"
      | "COMPLETED"
      | "FAILED"
      | "CANCELLED"
      | "TIMED_OUT"
      | "UNKNOWN";
    /** JobView */
    JobView: {
      /** Operation Id */
      operation_id: string;
      /** Job Id */
      job_id: string;
      /** Device Id */
      device_id: string;
      state: components["schemas"]["JobState"];
      /** Poll After Ms */
      poll_after_ms: number | null;
      /** Id */
      id: string;
      /** Owner Id */
      owner_id: string;
      /** Revision */
      revision: number;
      /** Progress */
      progress: number | null;
      /** Waiting Reason */
      waiting_reason: string | null;
      /** Progress Revision */
      progress_revision: number;
      /** Operation */
      operation: string;
      /** Timeout Ms */
      timeout_ms: number;
      /** Result */
      result: {
        [key: string]: unknown;
      } | null;
      /** Error */
      error: {
        [key: string]: unknown;
      } | null;
      /** Created At */
      created_at: string;
      /** Updated At */
      updated_at: string;
      /**
       * Outcome Available
       * @default true
       */
      outcome_available: boolean;
    };
    /** ListPage[ApprovalView] */
    ListPage_ApprovalView_: {
      /** Items */
      items: components["schemas"]["ApprovalView"][];
      /** Next Cursor */
      next_cursor: string | null;
      /**
       * Consistency
       * @default best_effort
       * @constant
       */
      consistency: "best_effort";
      /**
       * Sort
       * @default rowid_desc
       * @constant
       */
      sort: "rowid_desc";
    };
    /** ListPage[ArtifactView] */
    ListPage_ArtifactView_: {
      /** Items */
      items: components["schemas"]["ArtifactView"][];
      /** Next Cursor */
      next_cursor: string | null;
      /**
       * Consistency
       * @default best_effort
       * @constant
       */
      consistency: "best_effort";
      /**
       * Sort
       * @default rowid_desc
       * @constant
       */
      sort: "rowid_desc";
    };
    /** ListPage[AuditView] */
    ListPage_AuditView_: {
      /** Items */
      items: components["schemas"]["AuditView"][];
      /** Next Cursor */
      next_cursor: string | null;
      /**
       * Consistency
       * @default best_effort
       * @constant
       */
      consistency: "best_effort";
      /**
       * Sort
       * @default rowid_desc
       * @constant
       */
      sort: "rowid_desc";
    };
    /** ListPage[DeviceView] */
    ListPage_DeviceView_: {
      /** Items */
      items: components["schemas"]["DeviceView"][];
      /** Next Cursor */
      next_cursor: string | null;
      /**
       * Consistency
       * @default best_effort
       * @constant
       */
      consistency: "best_effort";
      /**
       * Sort
       * @default rowid_desc
       * @constant
       */
      sort: "rowid_desc";
    };
    /** ListPage[JobView] */
    ListPage_JobView_: {
      /** Items */
      items: components["schemas"]["JobView"][];
      /** Next Cursor */
      next_cursor: string | null;
      /**
       * Consistency
       * @default best_effort
       * @constant
       */
      consistency: "best_effort";
      /**
       * Sort
       * @default rowid_desc
       * @constant
       */
      sort: "rowid_desc";
    };
    /** LogExportCreateRequest */
    LogExportCreateRequest: {
      query?: components["schemas"]["LogQuery"];
      /**
       * Format
       * @default jsonl
       * @enum {string}
       */
      format: "json" | "jsonl";
      /** Idempotency Key */
      idempotency_key: string;
      /**
       * Max Rows
       * @default 10000
       */
      max_rows: number;
      /**
       * Max Bytes
       * @default 5242880
       */
      max_bytes: number;
    };
    /** LogExportReceiptView */
    LogExportReceiptView: {
      /** Id */
      id: string;
      /**
       * State
       * @enum {string}
       */
      state: "PENDING" | "SUCCEEDED" | "FAILED";
      /**
       * Format
       * @enum {string}
       */
      format: "json" | "jsonl";
      /** File Name */
      file_name: string;
      /** Rows */
      rows: number;
      /** Size Bytes */
      size_bytes: number;
      /**
       * Truncated
       * @default false
       */
      truncated: boolean;
      /** Sha256 */
      sha256?: string | null;
      /** Created At */
      created_at: string;
      /** Expires At */
      expires_at: string;
      /** Error */
      error?: string | null;
    };
    /** LogItem */
    LogItem: {
      /** Id */
      id: string;
      /**
       * Source
       * @enum {string}
       */
      source: "audit" | "diagnostic";
      /** Timestamp */
      timestamp: string;
      /** Event */
      event: string;
      /** Level */
      level: string;
      /** Message */
      message: string;
      /** Device Id */
      device_id: string;
      /** Request Id */
      request_id: string;
      /** Actor Id */
      actor_id: string;
      /** Fields */
      fields: {
        [key: string]: unknown;
      };
    };
    /** LogPage */
    LogPage: {
      /** Items */
      items: components["schemas"]["LogItem"][];
      /** Next Cursor */
      next_cursor?: string | null;
      /**
       * Dropped Count
       * @default 0
       */
      dropped_count: number;
    };
    /** LogQuery */
    LogQuery: {
      /** Source */
      source?: ("audit" | "diagnostic") | null;
      /** Device Id */
      device_id?: string | null;
      /** Request Id */
      request_id?: string | null;
      /** Actor Id */
      actor_id?: string | null;
      /** From Utc */
      from_utc?: string | null;
      /** To Utc */
      to_utc?: string | null;
      /**
       * Limit
       * @default 100
       */
      limit: number;
      /** Cursor */
      cursor?: string | null;
    };
    /** MaintenanceJobView */
    MaintenanceJobView: {
      /** Id */
      id: string;
      /**
       * Kind
       * @enum {string}
       */
      kind: "backup" | "restore" | "update";
      /**
       * State
       * @enum {string}
       */
      state: "PENDING" | "RUNNING" | "DEFERRED" | "SUCCEEDED" | "FAILED";
      /** Actor Id */
      actor_id: string;
      /** Realm Id */
      realm_id: string;
      /** Created At */
      created_at: string;
      /** Updated At */
      updated_at: string;
      /** Progress */
      progress?: number | null;
      /** Error */
      error?: string | null;
      /** Receipt Id */
      receipt_id?: string | null;
    };
    /** ManagedDeviceView */
    ManagedDeviceView: {
      /** Id */
      id: string;
      /** Name */
      name: string;
      /** Revoked */
      revoked: boolean;
      /** Epoch */
      epoch: number;
      /** Info */
      info: {
        [key: string]: unknown;
      };
      /** Group Ids */
      group_ids?: string[];
      /** Tags */
      tags?: string[];
      /** Revision */
      revision: number;
    };
    /** ManagementUserCreateRequest */
    ManagementUserCreateRequest: {
      /** Issuer */
      issuer: string;
      /** Subject */
      subject: string;
      /** Display Name */
      display_name: string;
      /**
       * Role
       * @enum {string}
       */
      role: "owner" | "admin" | "operator" | "viewer";
      /** Device Grants */
      device_grants?: string[];
      /** Output Grants */
      output_grants?: string[];
      /** Operation Grants */
      operation_grants?: string[];
    };
    /** ManagementUserPatchRequest */
    ManagementUserPatchRequest: {
      /** Role */
      role?: ("owner" | "admin" | "operator" | "viewer") | null;
      /** Active */
      active?: boolean | null;
      /** Device Grants */
      device_grants?: string[] | null;
      /** Output Grants */
      output_grants?: string[] | null;
      /** Operation Grants */
      operation_grants?: string[] | null;
    };
    /** ManagementUserView */
    ManagementUserView: {
      /** Id */
      id: string;
      /** Realm Id */
      realm_id: string;
      /** Issuer */
      issuer: string;
      /** Subject */
      subject: string;
      /** Display Name */
      display_name: string;
      /**
       * Role
       * @enum {string}
       */
      role: "owner" | "admin" | "operator" | "viewer";
      /** Active */
      active: boolean;
      /** Auth Revision */
      auth_revision: number;
      /** Device Grants */
      device_grants?: string[];
      /** Output Grants */
      output_grants?: string[];
      /** Operation Grants */
      operation_grants?: string[];
    };
    /** OperationInput */
    OperationInput: {
      /** Device Id */
      device_id: string;
      /**
       * Workspace Id
       * @default default
       */
      workspace_id: string;
      /** Operation */
      operation: string;
      /** Payload */
      payload: {
        [key: string]: unknown;
      };
      /** Timeout Ms */
      timeout_ms?: number | null;
      /**
       * Execution Mode
       * @default sync
       * @enum {string}
       */
      execution_mode: "sync" | "job";
      /** Idempotency Key */
      idempotency_key?: string | null;
      /**
       * Execution Profile Id
       * @default read_only
       * @enum {string}
       */
      execution_profile_id: "read_only" | "standard" | "trusted_personal";
      /** Approval Id */
      approval_id?: string | null;
    };
    /** RestoreCreateRequest */
    RestoreCreateRequest: {
      /** Backup Id */
      backup_id: string;
      /** Expected Instance Id */
      expected_instance_id: string;
      /** Expected Revision */
      expected_revision: number;
      /** Idempotency Key */
      idempotency_key: string;
      /**
       * Confirm
       * @constant
       */
      confirm: true;
    };
    /** RestorePreview */
    RestorePreview: {
      /** Backup Id */
      backup_id: string;
      /** Valid */
      valid: boolean;
      /** Schema Version */
      schema_version: number;
      /** Instance Id */
      instance_id: string;
      /**
       * Database Integrity
       * @enum {string}
       */
      database_integrity: "ok" | "failed";
      /** Warnings */
      warnings?: string[];
    };
    /** SettingsPatch */
    SettingsPatch: {
      /** Expected Revision */
      expected_revision: number;
      /** Changes */
      changes: {
        [key: string]: unknown;
      };
    };
    /** SettingsView */
    SettingsView: {
      /** Revision */
      revision: number;
      /** Values */
      values: {
        [key: string]: unknown;
      };
      /**
       * Restart Required
       * @default false
       */
      restart_required: boolean;
    };
    /** SupportBundleCreateRequest */
    SupportBundleCreateRequest: {
      /**
       * Log Limit
       * @default 200
       */
      log_limit: number;
      /**
       * Max Bytes
       * @default 5242880
       */
      max_bytes: number;
    };
    /** SupportBundleReceiptView */
    SupportBundleReceiptView: {
      /** Id */
      id: string;
      /** File Name */
      file_name: string;
      /** Sha256 */
      sha256: string;
      /** Size Bytes */
      size_bytes: number;
      /** Created At */
      created_at: string;
      /** Log Entries */
      log_entries: number;
    };
    /** TransferComplete */
    TransferComplete: {
      /** Size Bytes */
      size_bytes: number;
      /** Sha256 */
      sha256: string;
    };
    /** TransferCreate */
    TransferCreate: {
      /** Device Id */
      device_id: string;
      /**
       * Direction
       * @default upload
       * @enum {string}
       */
      direction: "upload" | "download";
      /** Operation Id */
      operation_id?: string | null;
      /** Output Id */
      output_id?: string | null;
      /** Artifact Id */
      artifact_id?: string | null;
      /** Size Bytes */
      size_bytes?: number | null;
      /** Sha256 */
      sha256?: string | null;
      /**
       * Media Type
       * @default application/octet-stream
       * @enum {string}
       */
      media_type:
        | "application/octet-stream"
        | "application/json"
        | "application/vnd.racp.output-stream"
        | "image/png"
        | "image/jpeg"
        | "text/plain";
    };
    /** UpdateApplyRequest */
    UpdateApplyRequest: {
      /** Release Id */
      release_id: string;
      /** Expected Revision */
      expected_revision: number;
      /** Idempotency Key */
      idempotency_key: string;
      /**
       * Confirm
       * @constant
       */
      confirm: true;
    };
    /** UpdateCandidateView */
    UpdateCandidateView: {
      /** Release Id */
      release_id: string;
      /** Version */
      version: string;
      /**
       * Platform
       * @constant
       */
      platform: "win-x64";
      /** Manifest Sha256 */
      manifest_sha256: string;
      /** Schema Rollback Compatible */
      schema_rollback_compatible: boolean;
      /** Checked At */
      checked_at: string;
    };
    /** UpdateCheckRequest */
    UpdateCheckRequest: {
      /** Expected Revision */
      expected_revision: number;
    };
    /** UpdateStatusView */
    UpdateStatusView: {
      /** Configured */
      configured: boolean;
      /** Current Version */
      current_version: string;
      /** Channel */
      channel: string;
      /** Feed Configured */
      feed_configured: boolean;
      /** Trust Key Configured */
      trust_key_configured: boolean;
      /** Automatic Check */
      automatic_check: boolean;
      /** Apply Enabled */
      apply_enabled: boolean;
      /** Reason */
      reason?: string | null;
    };
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
      /** Input */
      input?: unknown;
      /** Context */
      ctx?: Record<string, never>;
    };
    /** ConsoleEvent */
    ConsoleEvent: {
      /** Event Id */
      event_id: string;
      /**
       * Type
       * @enum {string}
       */
      type: "change" | "ready" | "refresh" | "session_expired";
      /** Observed At */
      observed_at: string;
      /** Resource */
      resource: string;
      /**
       * Device Id
       * @default null
       */
      device_id: string | null;
      /**
       * Operation Id
       * @default null
       */
      operation_id: string | null;
      /**
       * Full Refresh
       * @default false
       */
      full_refresh: boolean;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  management_status_api_v1_management_status_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["GatewayStatusView"];
        };
      };
    };
  };
  management_settings_api_v1_management_settings_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SettingsView"];
        };
      };
    };
  };
  management_settings_apply_api_v1_management_settings_put: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SettingsPatch"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SettingsView"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  management_settings_stage_api_v1_management_settings_stage_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SettingsPatch"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ConfigCheck"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  management_devices_api_v1_management_devices_get: {
    parameters: {
      query?: {
        search?: string | null;
        status_filter?: string | null;
        group_id?: string | null;
        limit?: number;
        cursor?: string | null;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["DevicePage"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  management_users_api_v1_management_users_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ManagementUserView"][];
        };
      };
    };
  };
  management_user_create_api_v1_management_users_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ManagementUserCreateRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ManagementUserView"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  management_user_patch_api_v1_management_users__user_id__patch: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        user_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ManagementUserPatchRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ManagementUserView"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  management_groups_api_v1_management_groups_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["DeviceGroupView"][];
        };
      };
    };
  };
  management_group_create_api_v1_management_groups_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["DeviceGroupCreateRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["DeviceGroupView"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  management_group_patch_api_v1_management_groups__group_id__patch: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        group_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["DeviceGroupPatchRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["DeviceGroupView"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  management_device_groups_api_v1_management_devices__device_id__groups_patch: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        device_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["DeviceGroupsPatch"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["DeviceMetadataView"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  management_logs_api_v1_management_logs_get: {
    parameters: {
      query?: {
        source?: ("audit" | "diagnostic") | null;
        device_id?: string | null;
        request_id?: string | null;
        actor_id?: string | null;
        from_utc?: string | null;
        to_utc?: string | null;
        limit?: number;
        cursor?: string | null;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["LogPage"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  management_log_export_create_api_v1_management_log_exports_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["LogExportCreateRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["LogExportReceiptView"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  management_log_export_status_api_v1_management_log_exports__export_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        export_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["LogExportReceiptView"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  management_log_export_download_api_v1_management_log_exports__export_id__download_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        export_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  management_backups_api_v1_management_backups_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["BackupSetView"][];
        };
      };
    };
  };
  management_backup_create_api_v1_management_backups_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["BackupCreateRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["BackupSetView"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  management_restore_preview_api_v1_management_backups__backup_id__restore_preview_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        backup_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["RestorePreview"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  management_restore_create_api_v1_management_restores_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["RestoreCreateRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["MaintenanceJobView"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  management_maintenance_job_api_v1_management_maintenance_jobs__job_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        job_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["MaintenanceJobView"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  management_update_status_api_v1_management_updates_status_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["UpdateStatusView"];
        };
      };
    };
  };
  management_update_check_api_v1_management_updates_check_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateCheckRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["UpdateCandidateView"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  management_update_apply_api_v1_management_updates_apply_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateApplyRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["MaintenanceJobView"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  management_support_bundle_create_api_v1_management_support_bundles_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SupportBundleCreateRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SupportBundleReceiptView"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  management_support_bundle_download_api_v1_management_support_bundles__bundle_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        bundle_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  console_setup_api_v1_console_setup_token_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
    };
  };
  console_session_api_v1_console_session_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ConsoleSession"];
        };
      };
    };
  };
  console_login_api_v1_console_session_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ConsoleLogin"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ConsoleSession"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  console_logout_api_v1_console_session_delete: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
    };
  };
  console_activity_api_v1_console_session_activity_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: string;
          };
        };
      };
    };
  };
  console_events_api_v1_events_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
    };
  };
  console_events_events_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
    };
  };
  doctor_api_v1_doctor_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["DoctorView"];
        };
      };
    };
  };
  health_healthz_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: string;
          };
        };
      };
    };
  };
  ready_readyz_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
    };
  };
  enrollment_api_v1_enrollment_tokens_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["EnrollmentInput"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  enroll_agent_v1_enroll_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["EnrollInput"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: string;
          };
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  devices_api_v1_devices_get: {
    parameters: {
      query?: {
        state?: string | null;
        limit?: number;
        cursor?: string | null;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ListPage_DeviceView_"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  device_api_v1_devices__device_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        device_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  revoke_api_v1_devices__device_id__revoke_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        device_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: string;
          };
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  device_handles_api_v1_devices__device_id__handles_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        device_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  resource_handle_api_v1_handles__handle_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        handle_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  rotate_api_v1_devices__device_id__credentials_rotate_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        device_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: string;
          };
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  execute_api_v1_operations_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["OperationInput"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  operation_api_v1_operations__operation_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        operation_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  cancel_api_v1_operations__operation_id__cancel_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        operation_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  resolutions_api_v1_operations__operation_id__resolutions_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        operation_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  operation_outputs_api_v1_operations__operation_id__outputs_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        operation_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  job_api_v1_jobs__job_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        job_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  cancel_job_api_v1_jobs__job_id__cancel_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        job_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  jobs_api_v1_jobs_get: {
    parameters: {
      query?: {
        device_id?: string | null;
        limit?: number;
        cursor?: string | null;
        state?: components["schemas"]["JobState"] | null;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ListPage_JobView_"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  approvals_api_v1_approvals_get: {
    parameters: {
      query?: {
        device_id?: string | null;
        state?: string | null;
        limit?: number;
        cursor?: string | null;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ListPage_ApprovalView_"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  approval_api_v1_approvals__approval_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        approval_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  approve_api_v1_approvals__approval_id__approve_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        approval_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  deny_api_v1_approvals__approval_id__deny_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        approval_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  execute_approved_api_v1_approvals__approval_id__execute_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        approval_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  audit_api_v1_audit_get: {
    parameters: {
      query?: {
        device_id?: string | null;
        event?: string | null;
        limit?: number;
        cursor?: string | null;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ListPage_AuditView_"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  upload_output_agent_v1_operations__operation_id__output_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        operation_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  artifact_api_v1_artifacts__artifact_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        artifact_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  content_api_v1_artifacts__artifact_id__content_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        artifact_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  artifact_list_api_v1_artifacts_get: {
    parameters: {
      query?: {
        device_id?: string | null;
        state?: string | null;
        limit?: number;
        cursor?: string | null;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ListPage_ArtifactView_"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  transfer_create_api_v1_artifact_transfers_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["TransferCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  transfer_get_api_v1_artifact_transfers__transfer_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        transfer_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  transfer_authorize_api_v1_artifact_transfers__transfer_id__authorize_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        transfer_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  transfer_download_api_v1_artifact_transfers__transfer_id__content_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        transfer_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  transfer_put_api_v1_artifact_transfers__transfer_id__content_put: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        transfer_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  transfer_complete_api_v1_artifact_transfers__transfer_id__complete_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        transfer_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["TransferComplete"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  artifact_gc_api_v1_artifacts_gc_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: number;
          };
        };
      };
    };
  };
}
