[package]
name = "racp-runtime"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
[dependencies]
racp-contract = { path = "../racp-contract" }
racp-core = { path = "../racp-core" }
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
tokio-util.workspace = true
reqwest.workspace = true
rustls.workspace = true
futures-util.workspace = true
url.workspace = true
chrono.workspace = true
base64.workspace = true
tokio-tungstenite.workspace = true
webpki-roots.workspace = true
sysinfo.workspace = true
rand.workspace = true
sha2.workspace = true
hmac = "0.12"
encoding_rs = "0.8"
unicode-casefold = "0.2"
subtle = "2"
whoami = "1"
[dev-dependencies]
tempfile.workspace = true

[target.'cfg(unix)'.dependencies]
libc = "0.2"
[target.'cfg(windows)'.dependencies]
windows-sys = { version = "0.61", features = ["Win32_Foundation", "Win32_System_Threading", "Win32_Security", "Win32_System_JobObjects", "Win32_System_Pipes", "Win32_Storage_FileSystem", "Win32_UI_WindowsAndMessaging", "Win32_System_Console"] }
