from enum import StrEnum


class JobState(StrEnum):
    QUEUED = "QUEUED"
    RUNNING = "RUNNING"
    WAITING = "WAITING"
    CANCEL_REQUESTED = "CANCEL_REQUESTED"
    RECONCILING = "RECONCILING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"
    TIMED_OUT = "TIMED_OUT"
    UNKNOWN = "UNKNOWN"


JOB_TERMINAL = frozenset({"COMPLETED", "FAILED", "CANCELLED", "TIMED_OUT", "UNKNOWN"})
OPERATION_JOB_STATE = {
    "ACCEPTED": "QUEUED",
    "DISPATCHED": "QUEUED",
    "RUNNING": "RUNNING",
    "CANCEL_REQUESTED": "CANCEL_REQUESTED",
    "RECONCILING": "RECONCILING",
    "SUCCEEDED": "COMPLETED",
    "FAILED": "FAILED",
    "CANCELLED": "CANCELLED",
    "TIMED_OUT": "TIMED_OUT",
    "UNKNOWN": "UNKNOWN",
}
