from typing import Protocol


class TerminalBackend(Protocol):
    pid: int

    def read(self) -> bytes | None: ...

    def write(self, data: bytes) -> int: ...

    def resize(self, cols: int, rows: int) -> None: ...

    def poll(self) -> int | None: ...

    def terminate(self) -> None: ...

    def finish(self) -> None: ...

    def close(self) -> None: ...
